//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantChain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Nullable<int> BillId { get; set; }
        public string Item { get; set; }
        public double SubTotal { get; set; }
        public int Quantity { get; set; }
        public double Total { get; set; }
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
    }
}
