//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantChain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int RestaurantId { get; set; }
        public string MenuImage { get; set; }
        public int ItemId { get; set; }
        public string Item { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
